### PR TITLE
Include minimalistic Golang library

### PR DESCRIPTION
**Pull request by FenrirUnbound**
When users choose to fork this repository and run it themselves, the main job should succeed to build a proper Golang package.

### CODE REVIEW

**Review by petey — APPROVED** [review]

**Comment by FenrirUnbound** [comment]
Configured the branch to have a Screwdriver project. Here is the build that ran: https://cd.screwdriver.cd/pipelines/9cb9f3b4b91028526e51e437640f4e3f8bb26cfa/build/d774fbf95df5334c7779ebe1eb99485005a23383

**Review by tkyi — APPROVED** [review]

**Comment by tkyi** [comment]
small one-liner README?

**Comment by FenrirUnbound** [comment]
@tkyi README updated

**Review by tkyi — APPROVED** [review]

**Pull request merged**
